### ISSUE TITLE
IA foto

### ISSUE THREAD

**Issue by omiras** [Singulars-2023-Front-End/Singluars#4]
## Objetivo

1. Buscar si existe una IA que dada una imagen te devuelva un texto descriptivo de la misma
2. Ver cuan se puede configurar esto (tono de la descripción, longitud de la descripción)
3. ¿Es gratuitua o de pago?

## Metodología

Una vez encontrada la IA, probadla en un poryecto que creeis vosotros, algo simple con HTML y JavaScript. Lo más sencilla possible para probarla.

Documentad en esta misma issue vuestras conclusiones.

**Comment by omiras** [comment]
- Hemos encontrado todas estas IAs possibles: 

1. IA 1
2. IA 2
3. etc.

**Comment by NordinMM** [comment]
1 - Photor.io : https://photor.io/ 

Descartamos ya que solo proporciona porcentajes sobre determinadas características de la imagen, identifica el producto o productos y los califica teniendo en cuenta su presencia en la imagen mediante porcentajes.



![Image](https://github.com/Singulars-2023-Front-End/Singluars/assets/109993508/c33af6fe-9f01-47c5-b541-bb8667c4589e)

**Comment by clopezva** [comment]
Visión Api de Google - https://cloud.google.com/vision?hl=es

Analiza e identifica objetos, lugares, personas y otros elementos presentes en una imagen y proporcionar una lista de etiquetas descriptivas.

![Image](https://github.com/Singulars-2023-Front-End/Singluars/assets/132434208/bc57ac33-dc39-4942-a32e-454925f46b09)


En el siguiente link  se muestra como podriamos implementar esta AI en conjunto con reconocimiento por cámara  y no solo por subida de imágenes.

https://umaar.com/dev-tips/118-cloud-vision-image-detect-javascript/  


Esta API opera bajo un modelo de precios basado en el consumo de recursos.  Esto significa que se nos cobrará en función del número de las solicitudes realizadas y la cantidad de datos procesados.


![Image](https://github.com/Singulars-2023-Front-End/Singluars/assets/132434208/798a6cde-cd6c-4065-bf8c-353f961e2de5)

**Comment by NordinMM** [comment]
3 - Computer Vision: https://www.microsoft.com/en-us/ai/ 
Descartamos por que solo existe mediante pago anual y extrae texto de las imágenes , no genera texto descriptivo referida la imagen.


![Image](https://github.com/Singulars-2023-Front-End/Singluars/assets/109993508/5395b0ab-4c46-4484-960a-9dfbc0ccd065)

**Comment by NordinMM** [comment]
4 - chatGPT : https://chat.openai.com/auth/login 

Descartamos debido a que acepta imágenes pero analiza y describe sin criterio alguno.

Imagen proporcionada:



![Image](https://github.com/Singulars-2023-Front-End/Singluars/assets/109993508/dc843671-f854-46a4-a3df-50c4446c35c3)


Respuesta recibida:

![Image](https://github.com/Singulars-2023-Front-End/Singluars/assets/109993508/4d4c3a98-ca7f-437f-a547-aeffa1798141)

**Comment by omiras** [comment]
@NordinMM @clopezva  Super buen trabajo de investigación. Mañana pueden contar las conclusiones al equipo. Quizás lo mejor sería dejar este informe tal cual y pasar a otra issue para avanzar en la práctica? Ustedes deciden mañana.

**Comment by omiras** [comment]
Me pregunto si la opción "4 - chatGPT" quizñas no hay que refinar la pregunta? Después de que te suelte todo ese rollo, decirle : "no, simplemente escribe el título de la imagen que acabo de subir y una descripción corta"

**Comment by NordinMM** [comment]
Sería interesante afinar ese punto, talvez funcione. Gracias por el consejo

**Comment by clopezva** [comment]
Se realizaron pruebas con ChatGPT proporcionandole un link de la imagen.

Concluimos que solo funciona si la URL contiene información sobre la imagen como por ejemplo. 

https://misshonolulu.com/wp-content/uploads/2022/01/**zapatos_novia_rosa_terciopelo**_misshonolulu_5.jpg 

![Image](https://github.com/Singulars-2023-Front-End/Singluars/assets/132434208/50223f0a-ee38-4a3a-abdf-5214d83694d4)

Ya que nos manda lo siguiente: La imagen que mencionas muestra unos zapatos de novia de color rosa en terciopelo. Los zapatos parecen tener un estilo elegante y femenino, con un diseño de tacón alto y una apariencia sofisticada.

Pero si mandamos otra URL la cual no contiene información en su link, nos comenta que:

https://conceptodefinicion.de/wp-content/uploads/2013/08/objeto.jpg

Basándome en la nueva URL proporcionada, desafortunadamente, como modelo de lenguaje de IA, no puedo acceder directamente a la imagen ni analizarla visualmente. Mi capacidad se limita al procesamiento del lenguaje natural.

Si tienes alguna descripción o información sobre la imagen en cuestión, puedes proporcionarla, y estaré encantado de ayudarte a generar texto relevante en base a esa información.

**Como podemos ver, no cumple los requisitos que necesitamos.**

**Comment by omiras** [comment]
Ok! La dejamos cerrada por el momento, gracias por el trabajo de invesigación!
